# This file was auto-generated by Fern from our API Definition.

import typing

InterviewsRetrieveRequestExpand = typing.Union[
    typing.Literal[
        "application",
        "application,job_interview_stage",
        "interviewers",
        "interviewers,application",
        "interviewers,application,job_interview_stage",
        "interviewers,job_interview_stage",
        "interviewers,organizer",
        "interviewers,organizer,application",
        "interviewers,organizer,application,job_interview_stage",
        "interviewers,organizer,job_interview_stage",
        "job_interview_stage",
        "organizer",
        "organizer,application",
        "organizer,application,job_interview_stage",
        "organizer,job_interview_stage",
    ],
    typing.Any,
]
