# This file was auto-generated by Fern from our API Definition.

import typing

from ....core import enum

T_Result = typing.TypeVar("T_Result")


class OpportunityStatusEnum(enum.StrEnum):
    """
    * `OPEN` - OPEN
    * `WON` - WON
    * `LOST` - LOST
    """

    OPEN = "OPEN"
    WON = "WON"
    LOST = "LOST"

    def visit(
        self,
        open: typing.Callable[[], T_Result],
        won: typing.Callable[[], T_Result],
        lost: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is OpportunityStatusEnum.OPEN:
            return open()
        if self is OpportunityStatusEnum.WON:
            return won()
        if self is OpportunityStatusEnum.LOST:
            return lost()
