# This file was auto-generated by Fern from our API Definition.

from .resources import accounting, ats, crm, filestorage, hris, ticketing
from .environment import MergeEnvironment
from .version import __version__

__all__ = ["MergeEnvironment", "__version__", "accounting", "ats", "crm", "filestorage", "hris", "ticketing"]
