# This file was auto-generated by Fern from our API Definition.

from .account import Account
from .account_classification import AccountClassification
from .account_currency import AccountCurrency
from .account_details import AccountDetails
from .account_details_and_actions import AccountDetailsAndActions
from .account_details_and_actions_integration import AccountDetailsAndActionsIntegration
from .account_details_and_actions_status_enum import AccountDetailsAndActionsStatusEnum
from .account_integration import AccountIntegration
from .account_request import AccountRequest
from .account_request_classification import AccountRequestClassification
from .account_request_currency import AccountRequestCurrency
from .account_request_status import AccountRequestStatus
from .account_response import AccountResponse
from .account_status import AccountStatus
from .account_status_enum import AccountStatusEnum
from .account_token import AccountToken
from .accounting_attachment import AccountingAttachment
from .accounting_attachment_request import AccountingAttachmentRequest
from .accounting_attachment_response import AccountingAttachmentResponse
from .accounting_period import AccountingPeriod
from .accounting_period_status import AccountingPeriodStatus
from .accounting_period_status_enum import AccountingPeriodStatusEnum
from .accounting_phone_number import AccountingPhoneNumber
from .accounting_phone_number_request import AccountingPhoneNumberRequest
from .address import Address
from .address_country import AddressCountry
from .address_request import AddressRequest
from .address_request_country import AddressRequestCountry
from .address_request_type import AddressRequestType
from .address_type import AddressType
from .address_type_enum import AddressTypeEnum
from .advanced_metadata import AdvancedMetadata
from .async_passthrough_reciept import AsyncPassthroughReciept
from .audit_log_event import AuditLogEvent
from .audit_log_event_event_type import AuditLogEventEventType
from .audit_log_event_role import AuditLogEventRole
from .available_actions import AvailableActions
from .balance_sheet import BalanceSheet
from .balance_sheet_company import BalanceSheetCompany
from .balance_sheet_currency import BalanceSheetCurrency
from .cash_flow_statement import CashFlowStatement
from .cash_flow_statement_company import CashFlowStatementCompany
from .cash_flow_statement_currency import CashFlowStatementCurrency
from .categories_enum import CategoriesEnum
from .category_enum import CategoryEnum
from .category_type_enum import CategoryTypeEnum
from .classification_enum import ClassificationEnum
from .common_model_scope_api import CommonModelScopeApi
from .common_model_scopes_body_request import CommonModelScopesBodyRequest
from .company_info import CompanyInfo
from .company_info_currency import CompanyInfoCurrency
from .contact import Contact
from .contact_addresses_item import ContactAddressesItem
from .contact_request import ContactRequest
from .contact_request_addresses_item import ContactRequestAddressesItem
from .contact_request_status import ContactRequestStatus
from .contact_response import ContactResponse
from .contact_status import ContactStatus
from .country_enum import CountryEnum
from .credit_note import CreditNote
from .credit_note_accounting_period import CreditNoteAccountingPeriod
from .credit_note_applied_payments_item import CreditNoteAppliedPaymentsItem
from .credit_note_company import CreditNoteCompany
from .credit_note_contact import CreditNoteContact
from .credit_note_currency import CreditNoteCurrency
from .credit_note_line_item import CreditNoteLineItem
from .credit_note_line_item_company import CreditNoteLineItemCompany
from .credit_note_line_item_item import CreditNoteLineItemItem
from .credit_note_payments_item import CreditNotePaymentsItem
from .credit_note_status import CreditNoteStatus
from .credit_note_status_enum import CreditNoteStatusEnum
from .credit_note_tracking_categories_item import CreditNoteTrackingCategoriesItem
from .currency_enum import CurrencyEnum
from .data_passthrough_request import DataPassthroughRequest
from .debug_mode_log import DebugModeLog
from .debug_model_log_summary import DebugModelLogSummary
from .enabled_actions_enum import EnabledActionsEnum
from .encoding_enum import EncodingEnum
from .error_validation_problem import ErrorValidationProblem
from .event_type_enum import EventTypeEnum
from .expense import Expense
from .expense_account import ExpenseAccount
from .expense_accounting_period import ExpenseAccountingPeriod
from .expense_company import ExpenseCompany
from .expense_contact import ExpenseContact
from .expense_currency import ExpenseCurrency
from .expense_line import ExpenseLine
from .expense_line_account import ExpenseLineAccount
from .expense_line_contact import ExpenseLineContact
from .expense_line_currency import ExpenseLineCurrency
from .expense_line_item import ExpenseLineItem
from .expense_line_request import ExpenseLineRequest
from .expense_line_request_account import ExpenseLineRequestAccount
from .expense_line_request_contact import ExpenseLineRequestContact
from .expense_line_request_currency import ExpenseLineRequestCurrency
from .expense_line_request_item import ExpenseLineRequestItem
from .expense_line_request_tracking_categories_item import ExpenseLineRequestTrackingCategoriesItem
from .expense_line_request_tracking_category import ExpenseLineRequestTrackingCategory
from .expense_line_tracking_categories_item import ExpenseLineTrackingCategoriesItem
from .expense_line_tracking_category import ExpenseLineTrackingCategory
from .expense_request import ExpenseRequest
from .expense_request_account import ExpenseRequestAccount
from .expense_request_accounting_period import ExpenseRequestAccountingPeriod
from .expense_request_company import ExpenseRequestCompany
from .expense_request_contact import ExpenseRequestContact
from .expense_request_currency import ExpenseRequestCurrency
from .expense_request_tracking_categories_item import ExpenseRequestTrackingCategoriesItem
from .expense_response import ExpenseResponse
from .expense_tracking_categories_item import ExpenseTrackingCategoriesItem
from .external_target_field_api import ExternalTargetFieldApi
from .external_target_field_api_response import ExternalTargetFieldApiResponse
from .field_mapping_api_instance import FieldMappingApiInstance
from .field_mapping_api_instance_remote_field import FieldMappingApiInstanceRemoteField
from .field_mapping_api_instance_remote_field_remote_endpoint_info import (
    FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo,
)
from .field_mapping_api_instance_response import FieldMappingApiInstanceResponse
from .field_mapping_api_instance_target_field import FieldMappingApiInstanceTargetField
from .field_mapping_instance_response import FieldMappingInstanceResponse
from .field_permission_deserializer import FieldPermissionDeserializer
from .field_permission_deserializer_request import FieldPermissionDeserializerRequest
from .income_statement import IncomeStatement
from .income_statement_company import IncomeStatementCompany
from .income_statement_currency import IncomeStatementCurrency
from .individual_common_model_scope_deserializer import IndividualCommonModelScopeDeserializer
from .individual_common_model_scope_deserializer_request import IndividualCommonModelScopeDeserializerRequest
from .invoice import Invoice
from .invoice_accounting_period import InvoiceAccountingPeriod
from .invoice_applied_payments_item import InvoiceAppliedPaymentsItem
from .invoice_company import InvoiceCompany
from .invoice_contact import InvoiceContact
from .invoice_currency import InvoiceCurrency
from .invoice_line_item import InvoiceLineItem
from .invoice_line_item_account import InvoiceLineItemAccount
from .invoice_line_item_currency import InvoiceLineItemCurrency
from .invoice_line_item_item import InvoiceLineItemItem
from .invoice_line_item_request import InvoiceLineItemRequest
from .invoice_line_item_request_account import InvoiceLineItemRequestAccount
from .invoice_line_item_request_currency import InvoiceLineItemRequestCurrency
from .invoice_line_item_request_item import InvoiceLineItemRequestItem
from .invoice_line_item_request_tracking_categories_item import InvoiceLineItemRequestTrackingCategoriesItem
from .invoice_line_item_request_tracking_category import InvoiceLineItemRequestTrackingCategory
from .invoice_line_item_tracking_categories_item import InvoiceLineItemTrackingCategoriesItem
from .invoice_line_item_tracking_category import InvoiceLineItemTrackingCategory
from .invoice_payments_item import InvoicePaymentsItem
from .invoice_purchase_orders_item import InvoicePurchaseOrdersItem
from .invoice_request import InvoiceRequest
from .invoice_request_company import InvoiceRequestCompany
from .invoice_request_contact import InvoiceRequestContact
from .invoice_request_currency import InvoiceRequestCurrency
from .invoice_request_payments_item import InvoiceRequestPaymentsItem
from .invoice_request_purchase_orders_item import InvoiceRequestPurchaseOrdersItem
from .invoice_request_status import InvoiceRequestStatus
from .invoice_request_tracking_categories_item import InvoiceRequestTrackingCategoriesItem
from .invoice_request_type import InvoiceRequestType
from .invoice_response import InvoiceResponse
from .invoice_status import InvoiceStatus
from .invoice_status_enum import InvoiceStatusEnum
from .invoice_tracking_categories_item import InvoiceTrackingCategoriesItem
from .invoice_type import InvoiceType
from .invoice_type_enum import InvoiceTypeEnum
from .issue import Issue
from .issue_status import IssueStatus
from .issue_status_enum import IssueStatusEnum
from .item import Item
from .item_company import ItemCompany
from .item_purchase_account import ItemPurchaseAccount
from .item_sales_account import ItemSalesAccount
from .item_status import ItemStatus
from .journal_entry import JournalEntry
from .journal_entry_accounting_period import JournalEntryAccountingPeriod
from .journal_entry_applied_payments_item import JournalEntryAppliedPaymentsItem
from .journal_entry_company import JournalEntryCompany
from .journal_entry_currency import JournalEntryCurrency
from .journal_entry_payments_item import JournalEntryPaymentsItem
from .journal_entry_posting_status import JournalEntryPostingStatus
from .journal_entry_request import JournalEntryRequest
from .journal_entry_request_company import JournalEntryRequestCompany
from .journal_entry_request_currency import JournalEntryRequestCurrency
from .journal_entry_request_payments_item import JournalEntryRequestPaymentsItem
from .journal_entry_request_posting_status import JournalEntryRequestPostingStatus
from .journal_entry_request_tracking_categories_item import JournalEntryRequestTrackingCategoriesItem
from .journal_entry_response import JournalEntryResponse
from .journal_entry_tracking_categories_item import JournalEntryTrackingCategoriesItem
from .journal_line import JournalLine
from .journal_line_account import JournalLineAccount
from .journal_line_currency import JournalLineCurrency
from .journal_line_request import JournalLineRequest
from .journal_line_request_account import JournalLineRequestAccount
from .journal_line_request_currency import JournalLineRequestCurrency
from .journal_line_request_tracking_categories_item import JournalLineRequestTrackingCategoriesItem
from .journal_line_request_tracking_category import JournalLineRequestTrackingCategory
from .journal_line_tracking_categories_item import JournalLineTrackingCategoriesItem
from .journal_line_tracking_category import JournalLineTrackingCategory
from .link_token import LinkToken
from .linked_account_status import LinkedAccountStatus
from .meta_response import MetaResponse
from .method_enum import MethodEnum
from .model_operation import ModelOperation
from .model_permission_deserializer import ModelPermissionDeserializer
from .model_permission_deserializer_request import ModelPermissionDeserializerRequest
from .multipart_form_field_request import MultipartFormFieldRequest
from .multipart_form_field_request_encoding import MultipartFormFieldRequestEncoding
from .paginated_account_details_and_actions_list import PaginatedAccountDetailsAndActionsList
from .paginated_account_list import PaginatedAccountList
from .paginated_accounting_attachment_list import PaginatedAccountingAttachmentList
from .paginated_accounting_period_list import PaginatedAccountingPeriodList
from .paginated_audit_log_event_list import PaginatedAuditLogEventList
from .paginated_balance_sheet_list import PaginatedBalanceSheetList
from .paginated_cash_flow_statement_list import PaginatedCashFlowStatementList
from .paginated_company_info_list import PaginatedCompanyInfoList
from .paginated_contact_list import PaginatedContactList
from .paginated_credit_note_list import PaginatedCreditNoteList
from .paginated_expense_list import PaginatedExpenseList
from .paginated_income_statement_list import PaginatedIncomeStatementList
from .paginated_invoice_list import PaginatedInvoiceList
from .paginated_issue_list import PaginatedIssueList
from .paginated_item_list import PaginatedItemList
from .paginated_journal_entry_list import PaginatedJournalEntryList
from .paginated_payment_list import PaginatedPaymentList
from .paginated_purchase_order_list import PaginatedPurchaseOrderList
from .paginated_sync_status_list import PaginatedSyncStatusList
from .paginated_tax_rate_list import PaginatedTaxRateList
from .paginated_tracking_category_list import PaginatedTrackingCategoryList
from .paginated_transaction_list import PaginatedTransactionList
from .paginated_vendor_credit_list import PaginatedVendorCreditList
from .patched_payment_request import PatchedPaymentRequest
from .patched_payment_request_account import PatchedPaymentRequestAccount
from .patched_payment_request_accounting_period import PatchedPaymentRequestAccountingPeriod
from .patched_payment_request_applied_to_lines_item import PatchedPaymentRequestAppliedToLinesItem
from .patched_payment_request_company import PatchedPaymentRequestCompany
from .patched_payment_request_contact import PatchedPaymentRequestContact
from .patched_payment_request_currency import PatchedPaymentRequestCurrency
from .patched_payment_request_tracking_categories_item import PatchedPaymentRequestTrackingCategoriesItem
from .patched_payment_request_type import PatchedPaymentRequestType
from .payment import Payment
from .payment_account import PaymentAccount
from .payment_accounting_period import PaymentAccountingPeriod
from .payment_applied_to_lines_item import PaymentAppliedToLinesItem
from .payment_company import PaymentCompany
from .payment_contact import PaymentContact
from .payment_currency import PaymentCurrency
from .payment_line_item import PaymentLineItem
from .payment_line_item_request import PaymentLineItemRequest
from .payment_request import PaymentRequest
from .payment_request_account import PaymentRequestAccount
from .payment_request_accounting_period import PaymentRequestAccountingPeriod
from .payment_request_applied_to_lines_item import PaymentRequestAppliedToLinesItem
from .payment_request_company import PaymentRequestCompany
from .payment_request_contact import PaymentRequestContact
from .payment_request_currency import PaymentRequestCurrency
from .payment_request_tracking_categories_item import PaymentRequestTrackingCategoriesItem
from .payment_request_type import PaymentRequestType
from .payment_response import PaymentResponse
from .payment_tracking_categories_item import PaymentTrackingCategoriesItem
from .payment_type import PaymentType
from .payment_type_enum import PaymentTypeEnum
from .posting_status_enum import PostingStatusEnum
from .purchase_order import PurchaseOrder
from .purchase_order_accounting_period import PurchaseOrderAccountingPeriod
from .purchase_order_company import PurchaseOrderCompany
from .purchase_order_currency import PurchaseOrderCurrency
from .purchase_order_delivery_address import PurchaseOrderDeliveryAddress
from .purchase_order_line_item import PurchaseOrderLineItem
from .purchase_order_line_item_currency import PurchaseOrderLineItemCurrency
from .purchase_order_line_item_item import PurchaseOrderLineItemItem
from .purchase_order_line_item_request import PurchaseOrderLineItemRequest
from .purchase_order_line_item_request_currency import PurchaseOrderLineItemRequestCurrency
from .purchase_order_line_item_request_item import PurchaseOrderLineItemRequestItem
from .purchase_order_request import PurchaseOrderRequest
from .purchase_order_request_company import PurchaseOrderRequestCompany
from .purchase_order_request_currency import PurchaseOrderRequestCurrency
from .purchase_order_request_delivery_address import PurchaseOrderRequestDeliveryAddress
from .purchase_order_request_status import PurchaseOrderRequestStatus
from .purchase_order_request_tracking_categories_item import PurchaseOrderRequestTrackingCategoriesItem
from .purchase_order_request_vendor import PurchaseOrderRequestVendor
from .purchase_order_response import PurchaseOrderResponse
from .purchase_order_status import PurchaseOrderStatus
from .purchase_order_status_enum import PurchaseOrderStatusEnum
from .purchase_order_tracking_categories_item import PurchaseOrderTrackingCategoriesItem
from .purchase_order_vendor import PurchaseOrderVendor
from .remote_data import RemoteData
from .remote_endpoint_info import RemoteEndpointInfo
from .remote_field_api import RemoteFieldApi
from .remote_field_api_coverage import RemoteFieldApiCoverage
from .remote_field_api_response import RemoteFieldApiResponse
from .remote_key import RemoteKey
from .remote_response import RemoteResponse
from .report_item import ReportItem
from .request_format_enum import RequestFormatEnum
from .response_type_enum import ResponseTypeEnum
from .role_enum import RoleEnum
from .selective_sync_configurations_usage_enum import SelectiveSyncConfigurationsUsageEnum
from .status_7_d_1_enum import Status7D1Enum
from .sync_status import SyncStatus
from .sync_status_status_enum import SyncStatusStatusEnum
from .tax_rate import TaxRate
from .tax_rate_company import TaxRateCompany
from .tracking_category import TrackingCategory
from .tracking_category_category_type import TrackingCategoryCategoryType
from .tracking_category_company import TrackingCategoryCompany
from .tracking_category_status import TrackingCategoryStatus
from .transaction import Transaction
from .transaction_account import TransactionAccount
from .transaction_accounting_period import TransactionAccountingPeriod
from .transaction_contact import TransactionContact
from .transaction_currency import TransactionCurrency
from .transaction_line_item import TransactionLineItem
from .transaction_line_item_currency import TransactionLineItemCurrency
from .transaction_line_item_item import TransactionLineItemItem
from .transaction_tracking_categories_item import TransactionTrackingCategoriesItem
from .validation_problem_source import ValidationProblemSource
from .vendor_credit import VendorCredit
from .vendor_credit_accounting_period import VendorCreditAccountingPeriod
from .vendor_credit_company import VendorCreditCompany
from .vendor_credit_currency import VendorCreditCurrency
from .vendor_credit_line import VendorCreditLine
from .vendor_credit_line_account import VendorCreditLineAccount
from .vendor_credit_tracking_categories_item import VendorCreditTrackingCategoriesItem
from .vendor_credit_vendor import VendorCreditVendor
from .warning_validation_problem import WarningValidationProblem
from .webhook_receiver import WebhookReceiver

__all__ = [
    "Account",
    "AccountClassification",
    "AccountCurrency",
    "AccountDetails",
    "AccountDetailsAndActions",
    "AccountDetailsAndActionsIntegration",
    "AccountDetailsAndActionsStatusEnum",
    "AccountIntegration",
    "AccountRequest",
    "AccountRequestClassification",
    "AccountRequestCurrency",
    "AccountRequestStatus",
    "AccountResponse",
    "AccountStatus",
    "AccountStatusEnum",
    "AccountToken",
    "AccountingAttachment",
    "AccountingAttachmentRequest",
    "AccountingAttachmentResponse",
    "AccountingPeriod",
    "AccountingPeriodStatus",
    "AccountingPeriodStatusEnum",
    "AccountingPhoneNumber",
    "AccountingPhoneNumberRequest",
    "Address",
    "AddressCountry",
    "AddressRequest",
    "AddressRequestCountry",
    "AddressRequestType",
    "AddressType",
    "AddressTypeEnum",
    "AdvancedMetadata",
    "AsyncPassthroughReciept",
    "AuditLogEvent",
    "AuditLogEventEventType",
    "AuditLogEventRole",
    "AvailableActions",
    "BalanceSheet",
    "BalanceSheetCompany",
    "BalanceSheetCurrency",
    "CashFlowStatement",
    "CashFlowStatementCompany",
    "CashFlowStatementCurrency",
    "CategoriesEnum",
    "CategoryEnum",
    "CategoryTypeEnum",
    "ClassificationEnum",
    "CommonModelScopeApi",
    "CommonModelScopesBodyRequest",
    "CompanyInfo",
    "CompanyInfoCurrency",
    "Contact",
    "ContactAddressesItem",
    "ContactRequest",
    "ContactRequestAddressesItem",
    "ContactRequestStatus",
    "ContactResponse",
    "ContactStatus",
    "CountryEnum",
    "CreditNote",
    "CreditNoteAccountingPeriod",
    "CreditNoteAppliedPaymentsItem",
    "CreditNoteCompany",
    "CreditNoteContact",
    "CreditNoteCurrency",
    "CreditNoteLineItem",
    "CreditNoteLineItemCompany",
    "CreditNoteLineItemItem",
    "CreditNotePaymentsItem",
    "CreditNoteStatus",
    "CreditNoteStatusEnum",
    "CreditNoteTrackingCategoriesItem",
    "CurrencyEnum",
    "DataPassthroughRequest",
    "DebugModeLog",
    "DebugModelLogSummary",
    "EnabledActionsEnum",
    "EncodingEnum",
    "ErrorValidationProblem",
    "EventTypeEnum",
    "Expense",
    "ExpenseAccount",
    "ExpenseAccountingPeriod",
    "ExpenseCompany",
    "ExpenseContact",
    "ExpenseCurrency",
    "ExpenseLine",
    "ExpenseLineAccount",
    "ExpenseLineContact",
    "ExpenseLineCurrency",
    "ExpenseLineItem",
    "ExpenseLineRequest",
    "ExpenseLineRequestAccount",
    "ExpenseLineRequestContact",
    "ExpenseLineRequestCurrency",
    "ExpenseLineRequestItem",
    "ExpenseLineRequestTrackingCategoriesItem",
    "ExpenseLineRequestTrackingCategory",
    "ExpenseLineTrackingCategoriesItem",
    "ExpenseLineTrackingCategory",
    "ExpenseRequest",
    "ExpenseRequestAccount",
    "ExpenseRequestAccountingPeriod",
    "ExpenseRequestCompany",
    "ExpenseRequestContact",
    "ExpenseRequestCurrency",
    "ExpenseRequestTrackingCategoriesItem",
    "ExpenseResponse",
    "ExpenseTrackingCategoriesItem",
    "ExternalTargetFieldApi",
    "ExternalTargetFieldApiResponse",
    "FieldMappingApiInstance",
    "FieldMappingApiInstanceRemoteField",
    "FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo",
    "FieldMappingApiInstanceResponse",
    "FieldMappingApiInstanceTargetField",
    "FieldMappingInstanceResponse",
    "FieldPermissionDeserializer",
    "FieldPermissionDeserializerRequest",
    "IncomeStatement",
    "IncomeStatementCompany",
    "IncomeStatementCurrency",
    "IndividualCommonModelScopeDeserializer",
    "IndividualCommonModelScopeDeserializerRequest",
    "Invoice",
    "InvoiceAccountingPeriod",
    "InvoiceAppliedPaymentsItem",
    "InvoiceCompany",
    "InvoiceContact",
    "InvoiceCurrency",
    "InvoiceLineItem",
    "InvoiceLineItemAccount",
    "InvoiceLineItemCurrency",
    "InvoiceLineItemItem",
    "InvoiceLineItemRequest",
    "InvoiceLineItemRequestAccount",
    "InvoiceLineItemRequestCurrency",
    "InvoiceLineItemRequestItem",
    "InvoiceLineItemRequestTrackingCategoriesItem",
    "InvoiceLineItemRequestTrackingCategory",
    "InvoiceLineItemTrackingCategoriesItem",
    "InvoiceLineItemTrackingCategory",
    "InvoicePaymentsItem",
    "InvoicePurchaseOrdersItem",
    "InvoiceRequest",
    "InvoiceRequestCompany",
    "InvoiceRequestContact",
    "InvoiceRequestCurrency",
    "InvoiceRequestPaymentsItem",
    "InvoiceRequestPurchaseOrdersItem",
    "InvoiceRequestStatus",
    "InvoiceRequestTrackingCategoriesItem",
    "InvoiceRequestType",
    "InvoiceResponse",
    "InvoiceStatus",
    "InvoiceStatusEnum",
    "InvoiceTrackingCategoriesItem",
    "InvoiceType",
    "InvoiceTypeEnum",
    "Issue",
    "IssueStatus",
    "IssueStatusEnum",
    "Item",
    "ItemCompany",
    "ItemPurchaseAccount",
    "ItemSalesAccount",
    "ItemStatus",
    "JournalEntry",
    "JournalEntryAccountingPeriod",
    "JournalEntryAppliedPaymentsItem",
    "JournalEntryCompany",
    "JournalEntryCurrency",
    "JournalEntryPaymentsItem",
    "JournalEntryPostingStatus",
    "JournalEntryRequest",
    "JournalEntryRequestCompany",
    "JournalEntryRequestCurrency",
    "JournalEntryRequestPaymentsItem",
    "JournalEntryRequestPostingStatus",
    "JournalEntryRequestTrackingCategoriesItem",
    "JournalEntryResponse",
    "JournalEntryTrackingCategoriesItem",
    "JournalLine",
    "JournalLineAccount",
    "JournalLineCurrency",
    "JournalLineRequest",
    "JournalLineRequestAccount",
    "JournalLineRequestCurrency",
    "JournalLineRequestTrackingCategoriesItem",
    "JournalLineRequestTrackingCategory",
    "JournalLineTrackingCategoriesItem",
    "JournalLineTrackingCategory",
    "LinkToken",
    "LinkedAccountStatus",
    "MetaResponse",
    "MethodEnum",
    "ModelOperation",
    "ModelPermissionDeserializer",
    "ModelPermissionDeserializerRequest",
    "MultipartFormFieldRequest",
    "MultipartFormFieldRequestEncoding",
    "PaginatedAccountDetailsAndActionsList",
    "PaginatedAccountList",
    "PaginatedAccountingAttachmentList",
    "PaginatedAccountingPeriodList",
    "PaginatedAuditLogEventList",
    "PaginatedBalanceSheetList",
    "PaginatedCashFlowStatementList",
    "PaginatedCompanyInfoList",
    "PaginatedContactList",
    "PaginatedCreditNoteList",
    "PaginatedExpenseList",
    "PaginatedIncomeStatementList",
    "PaginatedInvoiceList",
    "PaginatedIssueList",
    "PaginatedItemList",
    "PaginatedJournalEntryList",
    "PaginatedPaymentList",
    "PaginatedPurchaseOrderList",
    "PaginatedSyncStatusList",
    "PaginatedTaxRateList",
    "PaginatedTrackingCategoryList",
    "PaginatedTransactionList",
    "PaginatedVendorCreditList",
    "PatchedPaymentRequest",
    "PatchedPaymentRequestAccount",
    "PatchedPaymentRequestAccountingPeriod",
    "PatchedPaymentRequestAppliedToLinesItem",
    "PatchedPaymentRequestCompany",
    "PatchedPaymentRequestContact",
    "PatchedPaymentRequestCurrency",
    "PatchedPaymentRequestTrackingCategoriesItem",
    "PatchedPaymentRequestType",
    "Payment",
    "PaymentAccount",
    "PaymentAccountingPeriod",
    "PaymentAppliedToLinesItem",
    "PaymentCompany",
    "PaymentContact",
    "PaymentCurrency",
    "PaymentLineItem",
    "PaymentLineItemRequest",
    "PaymentRequest",
    "PaymentRequestAccount",
    "PaymentRequestAccountingPeriod",
    "PaymentRequestAppliedToLinesItem",
    "PaymentRequestCompany",
    "PaymentRequestContact",
    "PaymentRequestCurrency",
    "PaymentRequestTrackingCategoriesItem",
    "PaymentRequestType",
    "PaymentResponse",
    "PaymentTrackingCategoriesItem",
    "PaymentType",
    "PaymentTypeEnum",
    "PostingStatusEnum",
    "PurchaseOrder",
    "PurchaseOrderAccountingPeriod",
    "PurchaseOrderCompany",
    "PurchaseOrderCurrency",
    "PurchaseOrderDeliveryAddress",
    "PurchaseOrderLineItem",
    "PurchaseOrderLineItemCurrency",
    "PurchaseOrderLineItemItem",
    "PurchaseOrderLineItemRequest",
    "PurchaseOrderLineItemRequestCurrency",
    "PurchaseOrderLineItemRequestItem",
    "PurchaseOrderRequest",
    "PurchaseOrderRequestCompany",
    "PurchaseOrderRequestCurrency",
    "PurchaseOrderRequestDeliveryAddress",
    "PurchaseOrderRequestStatus",
    "PurchaseOrderRequestTrackingCategoriesItem",
    "PurchaseOrderRequestVendor",
    "PurchaseOrderResponse",
    "PurchaseOrderStatus",
    "PurchaseOrderStatusEnum",
    "PurchaseOrderTrackingCategoriesItem",
    "PurchaseOrderVendor",
    "RemoteData",
    "RemoteEndpointInfo",
    "RemoteFieldApi",
    "RemoteFieldApiCoverage",
    "RemoteFieldApiResponse",
    "RemoteKey",
    "RemoteResponse",
    "ReportItem",
    "RequestFormatEnum",
    "ResponseTypeEnum",
    "RoleEnum",
    "SelectiveSyncConfigurationsUsageEnum",
    "Status7D1Enum",
    "SyncStatus",
    "SyncStatusStatusEnum",
    "TaxRate",
    "TaxRateCompany",
    "TrackingCategory",
    "TrackingCategoryCategoryType",
    "TrackingCategoryCompany",
    "TrackingCategoryStatus",
    "Transaction",
    "TransactionAccount",
    "TransactionAccountingPeriod",
    "TransactionContact",
    "TransactionCurrency",
    "TransactionLineItem",
    "TransactionLineItemCurrency",
    "TransactionLineItemItem",
    "TransactionTrackingCategoriesItem",
    "ValidationProblemSource",
    "VendorCredit",
    "VendorCreditAccountingPeriod",
    "VendorCreditCompany",
    "VendorCreditCurrency",
    "VendorCreditLine",
    "VendorCreditLineAccount",
    "VendorCreditTrackingCategoriesItem",
    "VendorCreditVendor",
    "WarningValidationProblem",
    "WebhookReceiver",
]
