# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class BankFeedAccountAccountTypeEnum(str, enum.Enum):
    """
    * `BANK` - BANK
    * `CREDIT_CARD` - CREDIT_CARD
    """

    BANK = "BANK"
    CREDIT_CARD = "CREDIT_CARD"

    def visit(self, bank: typing.Callable[[], T_Result], credit_card: typing.Callable[[], T_Result]) -> T_Result:
        if self is BankFeedAccountAccountTypeEnum.BANK:
            return bank()
        if self is BankFeedAccountAccountTypeEnum.CREDIT_CARD:
            return credit_card()
