# This file was auto-generated by Fern from our API Definition.

import typing

from .transaction_currency_enum import TransactionCurrencyEnum

PurchaseOrderCurrency = typing.Union[TransactionCurrencyEnum, str]
