# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

if typing.TYPE_CHECKING:
    from .vendor_credit import VendorCredit
VendorCreditApplyLineForInvoiceVendorCredit = typing.Union[str, "VendorCredit"]
