# This file was auto-generated by Fern from our API Definition.

import typing

from ......core import enum

T_Result = typing.TypeVar("T_Result")


class ActivitiesRetrieveRequestShowEnumOrigins(enum.StrEnum):
    ACTIVITY_TYPE = "activity_type"
    ACTIVITY_TYPE_VISIBILITY = "activity_type,visibility"
    VISIBILITY = "visibility"

    def visit(
        self,
        activity_type: typing.Callable[[], T_Result],
        activity_type_visibility: typing.Callable[[], T_Result],
        visibility: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ActivitiesRetrieveRequestShowEnumOrigins.ACTIVITY_TYPE:
            return activity_type()
        if self is ActivitiesRetrieveRequestShowEnumOrigins.ACTIVITY_TYPE_VISIBILITY:
            return activity_type_visibility()
        if self is ActivitiesRetrieveRequestShowEnumOrigins.VISIBILITY:
            return visibility()
