# This file was auto-generated by Fern from our API Definition.

import typing

from ......core import enum

T_Result = typing.TypeVar("T_Result")


class AccountsListRequestRemoteFields(enum.StrEnum):
    CLASSIFICATION = "classification"
    CLASSIFICATION_STATUS = "classification,status"
    STATUS = "status"

    def visit(
        self,
        classification: typing.Callable[[], T_Result],
        classification_status: typing.Callable[[], T_Result],
        status: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is AccountsListRequestRemoteFields.CLASSIFICATION:
            return classification()
        if self is AccountsListRequestRemoteFields.CLASSIFICATION_STATUS:
            return classification_status()
        if self is AccountsListRequestRemoteFields.STATUS:
            return status()
