# This file was auto-generated by Fern from our API Definition.

import typing
from .screening_question_answer import ScreeningQuestionAnswer

ApplicationScreeningQuestionAnswersItem = typing.Union[str, ScreeningQuestionAnswer]
