# This file was auto-generated by Fern from our API Definition.

import typing

from ....core import enum

T_Result = typing.TypeVar("T_Result")


class LanguageEnum(enum.StrEnum):
    """
    * `en` - en
    * `de` - de
    """

    EN = "en"
    DE = "de"

    def visit(self, en: typing.Callable[[], T_Result], de: typing.Callable[[], T_Result]) -> T_Result:
        if self is LanguageEnum.EN:
            return en()
        if self is LanguageEnum.DE:
            return de()
