# This file was auto-generated by Fern from our API Definition.

from ....core.unchecked_base_model import UncheckedBaseModel
import typing
from .external_target_field_api import ExternalTargetFieldApi
import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2


class ExternalTargetFieldApiResponse(UncheckedBaseModel):
    file: typing.Optional[typing.List[ExternalTargetFieldApi]] = pydantic.Field(alias="File", default=None)
    folder: typing.Optional[typing.List[ExternalTargetFieldApi]] = pydantic.Field(alias="Folder", default=None)
    drive: typing.Optional[typing.List[ExternalTargetFieldApi]] = pydantic.Field(alias="Drive", default=None)
    group: typing.Optional[typing.List[ExternalTargetFieldApi]] = pydantic.Field(alias="Group", default=None)
    user: typing.Optional[typing.List[ExternalTargetFieldApi]] = pydantic.Field(alias="User", default=None)

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
