# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .attachments_list_request_expand_item import AttachmentsListRequestExpandItem
    from .attachments_list_request_remote_fields import AttachmentsListRequestRemoteFields
    from .attachments_list_request_show_enum_origins import AttachmentsListRequestShowEnumOrigins
    from .attachments_retrieve_request_expand_item import AttachmentsRetrieveRequestExpandItem
    from .attachments_retrieve_request_remote_fields import AttachmentsRetrieveRequestRemoteFields
    from .attachments_retrieve_request_show_enum_origins import AttachmentsRetrieveRequestShowEnumOrigins
_dynamic_imports: typing.Dict[str, str] = {
    "AttachmentsListRequestExpandItem": ".attachments_list_request_expand_item",
    "AttachmentsListRequestRemoteFields": ".attachments_list_request_remote_fields",
    "AttachmentsListRequestShowEnumOrigins": ".attachments_list_request_show_enum_origins",
    "AttachmentsRetrieveRequestExpandItem": ".attachments_retrieve_request_expand_item",
    "AttachmentsRetrieveRequestRemoteFields": ".attachments_retrieve_request_remote_fields",
    "AttachmentsRetrieveRequestShowEnumOrigins": ".attachments_retrieve_request_show_enum_origins",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AttachmentsListRequestExpandItem",
    "AttachmentsListRequestRemoteFields",
    "AttachmentsListRequestShowEnumOrigins",
    "AttachmentsRetrieveRequestExpandItem",
    "AttachmentsRetrieveRequestRemoteFields",
    "AttachmentsRetrieveRequestShowEnumOrigins",
]
