# This file was auto-generated by Fern from our API Definition.

import typing

from .attachment import Attachment

ArticleAttachments = typing.Union[typing.List[typing.Optional[typing.Any]], Attachment]
