# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class TicketsListRequestPriority(str, enum.Enum):
    HIGH = "HIGH"
    LOW = "LOW"
    NORMAL = "NORMAL"
    URGENT = "URGENT"

    def visit(
        self,
        high: typing.Callable[[], T_Result],
        low: typing.Callable[[], T_Result],
        normal: typing.Callable[[], T_Result],
        urgent: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is TicketsListRequestPriority.HIGH:
            return high()
        if self is TicketsListRequestPriority.LOW:
            return low()
        if self is TicketsListRequestPriority.NORMAL:
            return normal()
        if self is TicketsListRequestPriority.URGENT:
            return urgent()
