# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class UsersRetrieveRequestExpand(str, enum.Enum):
    ROLES = "roles"
    TEAMS = "teams"
    TEAMS_ROLES = "teams,roles"

    def visit(
        self,
        roles: typing.Callable[[], T_Result],
        teams: typing.Callable[[], T_Result],
        teams_roles: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is UsersRetrieveRequestExpand.ROLES:
            return roles()
        if self is UsersRetrieveRequestExpand.TEAMS:
            return teams()
        if self is UsersRetrieveRequestExpand.TEAMS_ROLES:
            return teams_roles()
