# This file was auto-generated by Fern. It is not intended for manual modification.

from __future__ import annotations
import typing
from types import TracebackType


class AssuranceAgent:
    """
    A handle to the running Merge Assurance background agent.
    """

    def shutdown(self, wait: bool = True, timeout_seconds: typing.Optional[float] = None) -> None:
        """
        Signals the background agent to shut down gracefully.
        """
        raise NotImplementedError("Assurance Agent shutdown implementation pending.")
    
    async def shutdown_async(self, wait: bool = True, timeout_seconds: typing.Optional[float] = None) -> None:
        """
        Asynchronously signals the background agent to shut down gracefully.
        """
        raise NotImplementedError("Async Assurance Agent shutdown implementation pending.")

    def __enter__(self) -> "AssuranceAgent":
        return self

    def __exit__(
        self,
        exc_type: typing.Optional[typing.Type[BaseException]],
        exc_val: typing.Optional[BaseException],
        exc_tb: typing.Optional[TracebackType],
    )-> None:
        self.shutdown()