# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ProjectsUsersListRequestExpandItem(str, enum.Enum):
    ROLES = "roles"
    TEAMS = "teams"

    def visit(self, roles: typing.Callable[[], T_Result], teams: typing.Callable[[], T_Result]) -> T_Result:
        if self is ProjectsUsersListRequestExpandItem.ROLES:
            return roles()
        if self is ProjectsUsersListRequestExpandItem.TEAMS:
            return teams()
