# This file was auto-generated by Fern from our API Definition.

import typing

from ....core import enum

T_Result = typing.TypeVar("T_Result")


class AvailabilityStatusEnum(enum.StrEnum):
    FREE = "FREE"
    BUSY = "BUSY"
    OUT_OF_OFFICE = "OUT_OF_OFFICE"
    WORKING_ELSEWHERE = "WORKING_ELSEWHERE"
    UNKNOWN = "UNKNOWN"

    def visit(
        self,
        free: typing.Callable[[], T_Result],
        busy: typing.Callable[[], T_Result],
        out_of_office: typing.Callable[[], T_Result],
        working_elsewhere: typing.Callable[[], T_Result],
        unknown: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is AvailabilityStatusEnum.FREE:
            return free()
        if self is AvailabilityStatusEnum.BUSY:
            return busy()
        if self is AvailabilityStatusEnum.OUT_OF_OFFICE:
            return out_of_office()
        if self is AvailabilityStatusEnum.WORKING_ELSEWHERE:
            return working_elsewhere()
        if self is AvailabilityStatusEnum.UNKNOWN:
            return unknown()
