# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class CalendarTypeEnum(str, enum.Enum):
    PERSONAL = "PERSONAL"
    SHARED = "SHARED"

    def visit(self, personal: typing.Callable[[], T_Result], shared: typing.Callable[[], T_Result]) -> T_Result:
        if self is CalendarTypeEnum.PERSONAL:
            return personal()
        if self is CalendarTypeEnum.SHARED:
            return shared()
