# This file was auto-generated by Fern from our API Definition.

import typing

TicketsListRequestRemoteFields = typing.Union[
    typing.Literal[
        "priority",
        "priority,status",
        "priority,status,ticket_type",
        "priority,ticket_type",
        "status",
        "status,ticket_type",
        "ticket_type",
    ],
    typing.Any,
]
