# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class TicketsViewersListRequestExpandItem(str, enum.Enum):
    TEAM = "team"
    USER = "user"

    def visit(self, team: typing.Callable[[], T_Result], user: typing.Callable[[], T_Result]) -> T_Result:
        if self is TicketsViewersListRequestExpandItem.TEAM:
            return team()
        if self is TicketsViewersListRequestExpandItem.USER:
            return user()
