# This file was auto-generated by Fern from our API Definition.

import typing

from .folder_permissions_item import FolderPermissionsItem
from .permission import Permission

FolderPermissions = typing.Union[str, Permission, typing.List[FolderPermissionsItem]]
