# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class SalesOrdersListRequestExpandItem(str, enum.Enum):
    COMPANY = "company"
    CUSTOMER = "customer"
    LINES = "lines"
    PAYMENT_TERM = "payment_term"
    SHIPPING_ADDRESS = "shipping_address"
    TRACKING_CATEGORIES = "tracking_categories"

    def visit(
        self,
        company: typing.Callable[[], T_Result],
        customer: typing.Callable[[], T_Result],
        lines: typing.Callable[[], T_Result],
        payment_term: typing.Callable[[], T_Result],
        shipping_address: typing.Callable[[], T_Result],
        tracking_categories: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is SalesOrdersListRequestExpandItem.COMPANY:
            return company()
        if self is SalesOrdersListRequestExpandItem.CUSTOMER:
            return customer()
        if self is SalesOrdersListRequestExpandItem.LINES:
            return lines()
        if self is SalesOrdersListRequestExpandItem.PAYMENT_TERM:
            return payment_term()
        if self is SalesOrdersListRequestExpandItem.SHIPPING_ADDRESS:
            return shipping_address()
        if self is SalesOrdersListRequestExpandItem.TRACKING_CATEGORIES:
            return tracking_categories()
