# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class InvoicesListRequestExpandItem(str, enum.Enum):
    ACCOUNTING_PERIOD = "accounting_period"
    APPLIED_CREDIT_NOTES = "applied_credit_notes"
    APPLIED_PAYMENTS = "applied_payments"
    APPLIED_VENDOR_CREDITS = "applied_vendor_credits"
    COMPANY = "company"
    CONTACT = "contact"
    EMPLOYEE = "employee"
    LINE_ITEMS = "line_items"
    PAYMENT_TERM = "payment_term"
    PAYMENTS = "payments"
    PURCHASE_ORDERS = "purchase_orders"
    TRACKING_CATEGORIES = "tracking_categories"

    def visit(
        self,
        accounting_period: typing.Callable[[], T_Result],
        applied_credit_notes: typing.Callable[[], T_Result],
        applied_payments: typing.Callable[[], T_Result],
        applied_vendor_credits: typing.Callable[[], T_Result],
        company: typing.Callable[[], T_Result],
        contact: typing.Callable[[], T_Result],
        employee: typing.Callable[[], T_Result],
        line_items: typing.Callable[[], T_Result],
        payment_term: typing.Callable[[], T_Result],
        payments: typing.Callable[[], T_Result],
        purchase_orders: typing.Callable[[], T_Result],
        tracking_categories: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is InvoicesListRequestExpandItem.ACCOUNTING_PERIOD:
            return accounting_period()
        if self is InvoicesListRequestExpandItem.APPLIED_CREDIT_NOTES:
            return applied_credit_notes()
        if self is InvoicesListRequestExpandItem.APPLIED_PAYMENTS:
            return applied_payments()
        if self is InvoicesListRequestExpandItem.APPLIED_VENDOR_CREDITS:
            return applied_vendor_credits()
        if self is InvoicesListRequestExpandItem.COMPANY:
            return company()
        if self is InvoicesListRequestExpandItem.CONTACT:
            return contact()
        if self is InvoicesListRequestExpandItem.EMPLOYEE:
            return employee()
        if self is InvoicesListRequestExpandItem.LINE_ITEMS:
            return line_items()
        if self is InvoicesListRequestExpandItem.PAYMENT_TERM:
            return payment_term()
        if self is InvoicesListRequestExpandItem.PAYMENTS:
            return payments()
        if self is InvoicesListRequestExpandItem.PURCHASE_ORDERS:
            return purchase_orders()
        if self is InvoicesListRequestExpandItem.TRACKING_CATEGORIES:
            return tracking_categories()
