name: CI Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    env:
      API_KEY: ${{ secrets.TEST_ORG_API_KEY }}
      ACCOUNT_TOKEN_ATS: ${{ secrets.TEST_ORG_ATS_LINKED_ACCOUNT_TOKEN }}
      ACCOUNT_TOKEN_HRIS: ${{ secrets.TEST_ORG_HRIS_LINKED_ACCOUNT_TOKEN }}

    name: CI Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.16

      - name: Install poetry
        run: |
          python -m pip install poetry==1.4.2

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install

      - name: Run tests
        run: |
          python -m poetry run python -m pytest -k ci_integration



