# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bank_info_account_type import BankInfoAccountType
from .bank_info_employee import BankInfoEmployee
from .remote_data import RemoteData


class BankInfo(UniversalBaseModel):
    """
    # The BankInfo Object

    ### Description

    The `BankInfo` object is used to represent the Bank Account information for an Employee.

    ### Usage Example

    Fetch from the `LIST BankInfo` endpoint and filter by `ID` to show all bank information.
    """

    id: typing.Optional[str]
    remote_id: typing.Optional[str] = pydantic.Field()
    """
    The third-party API ID of the matching object.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field()
    """
    The datetime that this object was created by Merge.
    """

    modified_at: typing.Optional[dt.datetime] = pydantic.Field()
    """
    The datetime that this object was modified by Merge.
    """

    employee: typing.Optional[BankInfoEmployee] = pydantic.Field()
    """
    The employee with this bank account.
    """

    account_number: typing.Optional[str] = pydantic.Field()
    """
    The account number.
    """

    routing_number: typing.Optional[str] = pydantic.Field()
    """
    The routing number.
    """

    bank_name: typing.Optional[str] = pydantic.Field()
    """
    The bank name.
    """

    account_type: typing.Optional[BankInfoAccountType] = pydantic.Field()
    """
    The bank account type
    
    - `SAVINGS` - SAVINGS
    - `CHECKING` - CHECKING
    """

    remote_created_at: typing.Optional[dt.datetime] = pydantic.Field()
    """
    When the matching bank object was created in the third party system.
    """

    remote_was_deleted: typing.Optional[bool] = pydantic.Field()
    """
    Indicates whether or not this object has been deleted in the third party platform.
    """

    field_mappings: typing.Optional[typing.Dict[str, typing.Any]]
    remote_data: typing.Optional[typing.List[RemoteData]]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
