# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class TimesheetEntriesListRequestOrderBy(str, enum.Enum):
    START_TIME_DESCENDING = "-start_time"
    START_TIME_ASCENDING = "start_time"

    def visit(
        self, start_time_descending: typing.Callable[[], T_Result], start_time_ascending: typing.Callable[[], T_Result]
    ) -> T_Result:
        if self is TimesheetEntriesListRequestOrderBy.START_TIME_DESCENDING:
            return start_time_descending()
        if self is TimesheetEntriesListRequestOrderBy.START_TIME_ASCENDING:
            return start_time_ascending()
